from litestar_email.backends import (
    BaseEmailBackend,
    ConsoleBackend,
    InMemoryBackend,
    MailgunBackend,
    ResendBackend,
    SendGridBackend,
    SESBackend,
    SMTPBackend,
    email_backend,
    get_backend,
    get_backend_class,
    list_backends,
)
from litestar_email.config import (
    AsyncServiceProvider,
    BackendConfig,
    EmailConfig,
    MailgunConfig,
    ResendConfig,
    SendGridConfig,
    SESConfig,
    SMTPConfig,
)
from litestar_email.exceptions import (
    EmailAuthenticationError,
    EmailBackendError,
    EmailConnectionError,
    EmailDeliveryError,
    EmailError,
    EmailRateLimitError,
    MissingDependencyError,
)
from litestar_email.message import EmailMessage, EmailMultiAlternatives
from litestar_email.plugin import EmailPlugin
from litestar_email.service import EmailService

__all__ = (
    "AsyncServiceProvider",
    "BackendConfig",
    "BaseEmailBackend",
    "ConsoleBackend",
    "EmailAuthenticationError",
    "EmailBackendError",
    "EmailConfig",
    "EmailConnectionError",
    "EmailDeliveryError",
    "EmailError",
    "EmailMessage",
    "EmailMultiAlternatives",
    "EmailPlugin",
    "EmailRateLimitError",
    "EmailService",
    "InMemoryBackend",
    "MailgunBackend",
    "MailgunConfig",
    "MissingDependencyError",
    "ResendBackend",
    "ResendConfig",
    "SESBackend",
    "SESConfig",
    "SMTPBackend",
    "SMTPConfig",
    "SendGridBackend",
    "SendGridConfig",
    "email_backend",
    "get_backend",
    "get_backend_class",
    "list_backends",
)
